# Generated by Django 3.2.4 on 2021-06-08 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('proteina', models.CharField(max_length=70)),
                ('acompanhamento', models.CharField(max_length=150)),
                ('salada', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Cadapio',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinas', models.CharField(max_length=100)),
                ('acompanhamentos', models.CharField(max_length=100)),
                ('saladas', models.CharField(max_length=80)),
                ('valor_refeicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sabor_bebida250', models.CharField(max_length=20, verbose_name='sabor de 250ml')),
                ('quantidade_bebida_250', models.CharField(max_length=20, verbose_name='quantidade bebida 250ml')),
                ('bebida_1lt', models.CharField(max_length=15)),
                ('quantidade_bebida_1lt', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
