# Generated by Django 3.2.4 on 2021-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_bebida_250',
            field=models.CharField(max_length=20, verbose_name='quant. bebida 250ml'),
        ),
    ]
