# Generated by Django 3.2.4 on 2021-06-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210606_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='saldas',
            new_name='saladas',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='usuraio',
            new_name='usuario',
        ),
    ]
