# Generated by Django 3.2.4 on 2021-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210612_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_bebida_1lt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_bebida_250',
            field=models.FloatField(verbose_name='quantidade bebida 250ml'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_refeicao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_refeicao',
            field=models.FloatField(),
        ),
    ]
