# Generated by Django 3.2.4 on 2021-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210606_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteina', models.CharField(max_length=70)),
                ('acompanhamento', models.CharField(max_length=100)),
                ('salada', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Cadapio',
            },
        ),
    ]
