# Generated by Django 3.2.4 on 2021-06-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210612_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_refeicao',
            field=models.IntegerField(),
        ),
    ]
