# Generated by Django 3.2.4 on 2021-06-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_pedido_quantidade_refeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_bebida_1lt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_bebida_250',
            field=models.IntegerField(verbose_name='quantidade bebida 250ml'),
        ),
    ]
