# Generated by Django 3.2.4 on 2021-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_cadapio_acompanhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadapio',
            name='nome',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
